# ========================
# TOMCAT
# ========================
server:
  tomcat:
    additional-tld-skip-patterns: '*.jar'
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# ========================
# SPRING
# ========================
logging:
  level:
    org.springframework: INFO 

spring:
  resources:
    static-locations: classpath:/launcherDir/,classpath:/public/
  devtools:
    restart:
      additional-exclude: launcherDir/**
  daßßtasource:
    url: ${DBURL:jdbc:postgresql://localhost:54322/pub}
    username: ${DBUSR:gretl}
    password: ${DBPWD:gretl}
    driver-class-name: org.postgresql.Driver
    hikari.maximumPoolSize: ${MAXIMUM_POOL_SIZE:10}
    hikari.connectionTimeout: 60000

# spring:
#     profiles:
#         active: test 



# ========================
# APPLICATION
# ========================
app:
  myVar: ${VAR:defaultValue}